### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Plugin-Helpers#1]
어느 서비스에서나 똑같은 footer 를 사용하고 싶습니다.

**Comment by aanoaa** [comment]
일반적으로 웹페이지에서의 영역을 크게 나누면
- header
- body
- footer

로 나눌 수 있습니다.

보통 header 에서는 서비스 로고, 메뉴바, 사용자 로그인 정보등을 표시합니다.
footer 는 저작권, 약관 및 기타 다른 서비스로의 링크등을 표시합니다.

footer 를 표시해서 좋은점은
- 우리는 이런곳이고 이런 서비스들을 하고 있다등의 홍보
- 잘 만들어진 느낌을 줍니다

이 아닐까 합니다.

@10001if 다른 서비스들을 참고해서 footer 에 어떠한 내용이 들어가면 좋을 지 고민해보세요.

**Comment by 10001if** [comment]
@aanoaa 고민해보고 다시 말씀드리겠습니다. ^^

**Comment by aanoaa** [comment]
일단은 https://story.theopencloset.net/ 이거 고대로 베껴서 사용하도록 합니다.

**Comment by aanoaa** [comment]
d1deb097735f6d500e4c05d5cfe28f25e7b0a9a9

**Comment by aanoaa** [comment]
`opencloset.css` 를 함께 사용해야 합니다.

**Comment by aanoaa** [comment]
이런식으로 사용

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet"href="/assets/components/opencloset.css/dist/css/opencloset.min.css">
  </head>
  <body>
    <div class="container">
      <div id="content">
        %= content
      </div>
    </div>
    %= footer
  </body>
</html>
```

**Comment by aanoaa** [comment]
은근슬쩍 해결되었습니다.
